// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkohqkgdntfzhwzsdwab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imprb2hxa2dkbnRmemh3enNkd2FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NjUzODUsImV4cCI6MjA3MjI0MTM4NX0.DOhTODMkW0JRi25GTY6qTkB3UDjTuzYTfCDLJibAqSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});